#remote_docker version: 20.10.14

version: 2.1

orbs:
  node: circleci/node@4.5.1
  python: circleci/python@2.0.3
  win: circleci/windows@4.1
  macos: circleci/macos@2.3.0
  browser-tools: circleci/browser-tools@1.4.0
  aws-ecr: circleci/aws-ecr@8.1.2

  

workflows:
  learning dynamic config:
    jobs:
      - testing-yarn


jobs:
  setup:
    docker:
      - image: cimg/base:current
    resource_class: medium #docker/machine/macos
    steps:
      - checkout





